### ISSUE TITLE
How can i upload an image? I am trying to drag the image till the text field, but i am always receiving this error message "后端配置项没有正常加载，上传插件不能正常使用！", What should i do to fix it?

### ISSUE THREAD

**Issue by eduardosfer** [SilentTiger/vue-ueditor#30]

**Comment by SilentTiger** [comment]
This error is through out from the core text editor inside. You need to config your server to use the upload function.
I'm afraid this vue-editor doesn't suit for you if you can not read Chinese, because this project is only a wrapper of [UEditor](https://github.com/fex-team/ueditor), the core text editor inside.

**Comment by eduardosfer** [comment]
Thaks for your answer, I already find another solution for my inssue. Thank
you anyway!
